"""DEFINITIVE TEST: does the Compose compiler plugin transform @Composable via
programmatic invocation (META-INF/services + -Xplugin), and what does the output
bytecode look like?
"""
import os, glob, shutil, subprocess, json

W = "/tmp/feas/run2"
shutil.rmtree(W, ignore_errors=True)
os.makedirs(W + "/src/p", exist_ok=True)
os.makedirs(W + "/out_noplugin", exist_ok=True)
os.makedirs(W + "/out_plugin", exist_ok=True)

open(W + "/src/p/Hello.kt", "w").write("""
package p

import androidx.compose.runtime.Composable

@Composable
fun Greeting(name: String) {
    println("hello " + name)
}
""")

COMPILER_JARS = [
    "kotlin-daemon-embeddable-2.0.21.jar", "kotlin-reflect-1.6.10.jar",
    "kotlin-script-runtime-2.0.21.jar", "trove4j-1.0.20200330.jar",
    "annotations-13.0.jar", "kotlinx-coroutines-core-jvm-1.8.1.jar",
    "kotlin-stdlib-2.0.21.jar", "kotlin-compiler-embeddable-2.0.21.jar",
]
TOOLCP = ":".join("/tmp/feas/jars/" + j for j in COMPILER_JARS)
COMPOSE_RT = "/tmp/feas/jars/cra/classes.jar"
PLUGIN = "/tmp/feas/jars/kotlin-compose-compiler-plugin-embeddable-2.0.21.jar"
USERCP = COMPOSE_RT + ":" + "/tmp/feas/jars/kotlin-stdlib-2.0.21.jar"

def compile_to(desc, outdir, with_plugin):
    args = ["java", "-cp", TOOLCP, "org.jetbrains.kotlin.cli.jvm.K2JVMCompiler",
            "-no-stdlib", "-classpath", USERCP, "-d", outdir]
    if with_plugin:
        args += ["-Xplugin=" + PLUGIN,
                 "-P", "plugin:androidx.compose.compiler.plugins.kotlin:liveLiteralsEnabled=false"]
    args += [W + "/src"]
    print(f"\n######## {desc}")
    r = subprocess.run(args, capture_output=True, text=True, timeout=900)
    print("exit:", r.returncode)
    o = r.stdout + r.stderr
    if o.strip(): print(o[-3000:])
    return r.returncode

compile_to("A) NO compose plugin", W + "/out_noplugin", False)
compile_to("B) WITH compose plugin (-Xplugin + service discovery)", W + "/out_plugin", True)

print("\n######## compare generated bytecode")
for label, d in [("NO PLUGIN", W + "/out_noplugin"), ("WITH PLUGIN", W + "/out_plugin")]:
    print(f"\n--- {label}")
    for f in sorted(glob.glob(d + "/**/*.class", recursive=True)):
        data = open(f, "rb").read()
        markers = [m for m in [b"Composer", b"composer", b"Composable", b"ComposableSingletons",
                               b"$composer", b"updateChangedFlags", b"SourceInformation"]
                   if m in data]
        print(f"   {os.path.relpath(f, d)}  size={len(data)}  markers={[m.decode() for m in markers]}")

# javap the composable
for label, d in [("NO PLUGIN", W + "/out_noplugin"), ("WITH PLUGIN", W + "/out_plugin")]:
    print(f"\n######## javap {label}")
    for f in glob.glob(d + "/p/*.class"):
        r = subprocess.run(["javap", "-p", "-c", f], capture_output=True, text=True)
        txt = r.stdout
        print(f"--- {os.path.basename(f)}")
        print(txt[:2600])
